Blockly.Msg.BASIC_LED16X8_GFX_TITLE = "LED16X8 DOT";
Blockly.Msg.BASIC_LED16X8_GFX_TOOLTIP = "Display selected dot on LED 16X8";
Blockly.Msg.BASIC_LED16X8_GFX_HELPURL = "";

Blockly.Msg.BASIC_LED16X8_CLR_GFX_TITLE = "Clear LED16X8";
Blockly.Msg.BASIC_LED16X8_CLR_GFX_TOOLTIP = "Clear LED16X8";
Blockly.Msg.BASIC_LED16X8_CLR_GFX_HELPURL = "";

Blockly.Msg.LED16X8_GFX_TITLE = "LED16X8 DOT";
Blockly.Msg.LED16X8_GFX_TOOLTIP = "LED16X8 DOT";
Blockly.Msg.LED16X8_GFX_HELPURL = "";

Blockly.Msg.GFX_TYPE = "Type";

Blockly.Msg.GFX_TYPE_PLOT = "Plot";
Blockly.Msg.GFX_TYPE_UNPLOT = "Unplot";
Blockly.Msg.GFX_TYPE_TOGGLE = "Toggle";
Blockly.Msg.GFX_TYPE_BAR = "Bar Graph";

Blockly.Msg.LED16X8_MOVE_TITLE = "LED16X8 MOVE";
Blockly.Msg.LED16X8_MOVE_TOOLTIP = "LED16X8 MOVE";
Blockly.Msg.LED16X8_MOVE_HELPURL = "";

Blockly.Msg.LED16X8_GFX_STACK_TITLE = "LED16X8 DOT STACK";
Blockly.Msg.LED16X8_GFX_STACK_TOOLTIP = "LED16X8 DOT STACK";
Blockly.Msg.LED16X8_GFX_STACK_HELPURL = "";

Blockly.Msg.GFX_TYPE_ROTATE = "ROTATE";
Blockly.Msg.GFX_TYPE_SHIFT = "SHIFT";
Blockly.Msg.GFX_TYPE_RIGHT = "RIGHT";
Blockly.Msg.GFX_TYPE_LEFT = "LEFT";
